[package]
name = "weekit"
version = "0.1.0"
authors = ["Tim Burks <timburks@google.com>"]

[dependencies]
libc = "0.2.0"
quick-xml = "0.12.0"
rand = "0.5.0-pre.1"
lazy_static = "1.0.0"
reqwest = "0.6.2"
chrono = "0.4.6"
